mode: encrypt             # encrypt 或 decrypt
laddr: ":8888"            # 本地监听端口
raddr: "1.2.3.4:1234"     # 转发目标地址
key: "1234567890abcdef"   # 16字节密钥
auth: "mytoken"           # 双向认证密钥
bindip: "0.0.0.0"         # 监听地址（默认 0.0.0.0，可省略）
