name: Go Android ARM64 Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-android-arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Install Android NDK (r25b)
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        mv android-ndk-r25b $HOME/android-ndk

    - name: Build for Android arm64
      env:
        GOOS: android
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
        PATH: $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
      run: |
        mkdir -p dist
        go build -v -o dist/keyforward-android-arm64 ./...

    - name: Compress Binary
      run: |
        cd dist
        tar -czf keyforward-android-arm64.tar.gz keyforward-android-arm64
        rm keyforward-android-arm64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-arm64-build
        path: dist/
