name: Go Selective Cross-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-windows-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm
          - goos: windows
            goarch: amd64
          - goos: android
            goarch: arm

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        mkdir -p dist
        output="keyforward-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output="${output}.exe"
        fi
        go build -o "dist/$output" ./...

    - name: Compress Binary
      run: |
        cd dist
        base="keyforward-${{ matrix.goos }}-${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          zip "${base}.zip" "${base}.exe"
          rm "${base}.exe"
        else
          tar -czf "${base}.tar.gz" "${base}"
          rm "${base}"
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: builds-linux-windows-android
        path: dist/

  build-macos-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Build for darwin/arm64
      env:
        GOOS: darwin
        GOARCH: arm64
      run: |
        mkdir -p dist
        go build -o dist/keyforward-darwin-arm64 ./...

    - name: Compress Binary
      run: |
        cd dist
        tar -czf keyforward-darwin-arm64.tar.gz keyforward-darwin-arm64
        rm keyforward-darwin-arm64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-macos-arm64
        path: dist/
